# Generated by Django 4.1.5 on 2023-01-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('princelabapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
